apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "node-feature-discovery-operator.fullname" . }}-metrics-reader
rules:
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
