apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: nfd-controller-manager
  name: nfd-controller-manager-metrics-service
  namespace: {{ include "node-feature-discovery-operator.namespace" . }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: nfd-controller-manager
