apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "node-feature-discovery-operator.fullname" . }}-master
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "node-feature-discovery-operator.fullname" . }}-master
subjects:
- kind: ServiceAccount
  name: nfd-master
  namespace: {{ include "node-feature-discovery-operator.namespace" . }}
