apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "node-feature-discovery-operator.fullname" . }}-worker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "node-feature-discovery-operator.fullname" . }}-worker
subjects:
- kind: ServiceAccount
  name: nfd-worker
  namespace: {{ include "node-feature-discovery-operator.namespace" . }}
